### ISSUE TITLE
Steps to use on browser/WASM

### ISSUE THREAD

**Issue by Jonarod** [LaurentMazare/candle#234]
Hello thank you for sharing this crate !!

Would it be possible to get the steps/code to reproduce the llama2.c web example [https://laurentmazare.github.io/candle-llama2/](https://laurentmazare.github.io/candle-llama2/) (compiling to wasm seems ok, but I am quite struggling to generate the corresponding JS glue-code to make it all work).

Again, thank you for your heavy work, really appreciated. :)

**Comment by LaurentMazare** [comment]
Actually I added some instructions in the main readme earlier today, they probably are not straightforward though, what you want to do is after checking out the current github tip is
```bash
# go into the proper directory
cd candle-wasm-examples/llama2-c

# retrieve the weight and tokenizer config files
wget https://karpathy.ai/llama2c/model.bin
wget https://github.com/karpathy/llama2.c/raw/master/tokenizer.bin

# use trunk to build everything :)
trunk serve --release --public-url /candle-llama2/ --port 8081
```

This should generate some `dist` directory in the current directory with everything that you need to deploy. You may have to install trunk, e.g. `cargo install trunk`. Note that this will have to be deployed to some `https://foo/candle-llama2` url. You can tweak the `--public-url` flag to customize this.

Let me know if any of these steps is causing issue and hopefully we can also update the readme instructions to make them clearer.

**Comment by Jonarod** [comment]
I am so sorry I actually tried yesterday night but only filled the issue on the morning, I did not see overnight readme.md push... 

I see, never used Trunk so far, I understand it builds wasm + js code at once and serves it right away. Cool.
Any advantages over using `wasm-pack`? Just curious :)

Thanks !

**Comment by LaurentMazare** [comment]
This project is the first time I'm using `trunk` rather than doing things manually, mostly because the `yew` documentation now recommends it. I actually find it quite nice: it automates all the different steps for you, and nicely packs what you have to deploy together in a single repo (and you just have to add some specific tags in `index.html` to specify the assets it needs to include).

**Comment by Jonarod** [comment]
Nice, will give it a try then :)
